# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sc_2015LB_commute <- function(D, K) {
    .Call('_T4cluster_sc_2015LB_commute', PACKAGE = 'T4cluster', D, K)
}

cpp_scNJW <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scNJW', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_scSM <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scSM', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_scUL <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scUL', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_sc05Z <- function(D, K, nnbd, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc05Z', PACKAGE = 'T4cluster', D, K, nnbd, usekmeans, maxiter)
}

cpp_sc09G <- function(D, K, nnbd, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc09G', PACKAGE = 'T4cluster', D, K, nnbd, usekmeans, maxiter)
}

cpp_sc10Z <- function(D, K, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc10Z', PACKAGE = 'T4cluster', D, K, usekmeans, maxiter)
}

cpp_sc11Y <- function(idmat, distmat, K, usekmeans, maxiter, rho) {
    .Call('_T4cluster_cpp_sc11Y', PACKAGE = 'T4cluster', idmat, distmat, K, usekmeans, maxiter, rho)
}

cpp_sc12L <- function(D, K, usekmeans, maxiter, sigma) {
    .Call('_T4cluster_cpp_sc12L', PACKAGE = 'T4cluster', D, K, usekmeans, maxiter, sigma)
}

src_pcm <- function(clmat) {
    .Call('_T4cluster_src_pcm', PACKAGE = 'T4cluster', clmat)
}

src_psm <- function(clmat) {
    .Call('_T4cluster_src_psm', PACKAGE = 'T4cluster', clmat)
}

arma_kmeans_random <- function(X, k, maxiter) {
    .Call('_T4cluster_arma_kmeans_random', PACKAGE = 'T4cluster', X, k, maxiter)
}

arma_kmeans_kmeanspp <- function(X, init, k, maxiter) {
    .Call('_T4cluster_arma_kmeans_kmeanspp', PACKAGE = 'T4cluster', X, init, k, maxiter)
}

cpp_shortestpath <- function(locs, dists) {
    .Call('_T4cluster_cpp_shortestpath', PACKAGE = 'T4cluster', locs, dists)
}

cpp_pdist <- function(X, p) {
    .Call('_T4cluster_cpp_pdist', PACKAGE = 'T4cluster', X, p)
}

cpp_pdist2 <- function(X, Y, p) {
    .Call('_T4cluster_cpp_pdist2', PACKAGE = 'T4cluster', X, Y, p)
}

cpp_pdistMP <- function(X, p, nCores) {
    .Call('_T4cluster_cpp_pdistMP', PACKAGE = 'T4cluster', X, p, nCores)
}

label_kmeans <- function(data, K, maxiter) {
    .Call('_T4cluster_label_kmeans', PACKAGE = 'T4cluster', data, K, maxiter)
}

label_gmm <- function(data, K, maxiter) {
    .Call('_T4cluster_label_gmm', PACKAGE = 'T4cluster', data, K, maxiter)
}

sc_unnormalized <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_unnormalized', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

sc_normalNJW <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_normalNJW', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

sc_normalSM <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_normalSM', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

