# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

src_pcm <- function(clmat) {
    .Call('_T4cluster_src_pcm', PACKAGE = 'T4cluster', clmat)
}

src_psm <- function(clmat) {
    .Call('_T4cluster_src_psm', PACKAGE = 'T4cluster', clmat)
}

coreset_18B <- function(X, K, M, maxiter) {
    .Call('_T4cluster_coreset_18B', PACKAGE = 'T4cluster', X, K, M, maxiter)
}

fpp_pdist_lp <- function(vect, vecf, myp) {
    .Call('_T4cluster_fpp_pdist_lp', PACKAGE = 'T4cluster', vect, vecf, myp)
}

gauss_w2median <- function(weight, mean, vars, maxiter = 100L, abstol = 1e-8) {
    .Call('_T4cluster_gauss_w2median', PACKAGE = 'T4cluster', weight, mean, vars, maxiter, abstol)
}

eval_label <- function(X, parMU, parSIG, parPI) {
    .Call('_T4cluster_eval_label', PACKAGE = 'T4cluster', X, parMU, parSIG, parPI)
}

gmm_skeleton <- function(X, k) {
    .Call('_T4cluster_gmm_skeleton', PACKAGE = 'T4cluster', X, k)
}

gmm_armadillo <- function(X, k, maxiter, usediag) {
    .Call('_T4cluster_gmm_armadillo', PACKAGE = 'T4cluster', X, k, maxiter, usediag)
}

gmm_11R <- function(X, K, lambda, maxiter, usediag) {
    .Call('_T4cluster_gmm_11R', PACKAGE = 'T4cluster', X, K, lambda, maxiter, usediag)
}

gmm_16Gfix <- function(X, k, weight, maxiter, usediag) {
    .Call('_T4cluster_gmm_16Gfix', PACKAGE = 'T4cluster', X, k, weight, maxiter, usediag)
}

gmm_combine_wsum <- function(gmmlist, weight) {
    .Call('_T4cluster_gmm_combine_wsum', PACKAGE = 'T4cluster', gmmlist, weight)
}

gmm_density <- function(coords, weight, mean, variance) {
    .Call('_T4cluster_gmm_density', PACKAGE = 'T4cluster', coords, weight, mean, variance)
}

gmm_pdist_wass2 <- function(mean, variance) {
    .Call('_T4cluster_gmm_pdist_wass2', PACKAGE = 'T4cluster', mean, variance)
}

gmm_w2barycenter <- function(weight, mean, vars) {
    .Call('_T4cluster_gmm_w2barycenter', PACKAGE = 'T4cluster', weight, mean, vars)
}

cpp_collapse_W2 <- function(weight, mean, vars) {
    .Call('_T4cluster_cpp_collapse_W2', PACKAGE = 'T4cluster', weight, mean, vars)
}

cpp_collapse_MPM <- function(weight, mean, vars) {
    .Call('_T4cluster_cpp_collapse_MPM', PACKAGE = 'T4cluster', weight, mean, vars)
}

cpp_reduction_1990S <- function(weight, mean, vars, M) {
    .Call('_T4cluster_cpp_reduction_1990S', PACKAGE = 'T4cluster', weight, mean, vars, M)
}

cpp_reduction_2003W <- function(weight, mean, vars, M) {
    .Call('_T4cluster_cpp_reduction_2003W', PACKAGE = 'T4cluster', weight, mean, vars, M)
}

cpp_reduction_2007R <- function(weight, mean, vars, M) {
    .Call('_T4cluster_cpp_reduction_2007R', PACKAGE = 'T4cluster', weight, mean, vars, M)
}

cpp_gmmcombine_tsl <- function(weight, mean, variance) {
    .Call('_T4cluster_cpp_gmmcombine_tsl', PACKAGE = 'T4cluster', weight, mean, variance)
}

cpp_barybregman15 <- function(listdXY, marginals, weights, p, lambda, maxiter, abstol, printer, initvec) {
    .Call('_T4cluster_cpp_barybregman15', PACKAGE = 'T4cluster', listdXY, marginals, weights, p, lambda, maxiter, abstol, printer, initvec)
}

cpp_gmmdist_l2 <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_l2', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_base <- function(mean1, variance1, mean2, variance2, basedist) {
    .Call('_T4cluster_cpp_gmmdist_base', PACKAGE = 'T4cluster', mean1, variance1, mean2, variance2, basedist)
}

cpp_gmmdist_cs <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_cs', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_jr <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_jr', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_tsl <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_tsl', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klga <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_klga', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klsel <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_T4cluster_cpp_gmmdist_klsel', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_he <- function(weight1, mean1, variance1, weight2, mean2, variance2, theta) {
    .Call('_T4cluster_cpp_gmmdist_he', PACKAGE = 'T4cluster', weight1, mean1, variance1, weight2, mean2, variance2, theta)
}

arma_kmeans_random <- function(X, k, maxiter) {
    .Call('_T4cluster_arma_kmeans_random', PACKAGE = 'T4cluster', X, k, maxiter)
}

arma_kmeans_kmeanspp <- function(X, init, k, maxiter) {
    .Call('_T4cluster_arma_kmeans_kmeanspp', PACKAGE = 'T4cluster', X, init, k, maxiter)
}

sc_2015LB_commute <- function(D, K) {
    .Call('_T4cluster_sc_2015LB_commute', PACKAGE = 'T4cluster', D, K)
}

cpp_scNJW <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scNJW', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_scSM <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scSM', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_scUL <- function(D, K, sigma, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_scUL', PACKAGE = 'T4cluster', D, K, sigma, usekmeans, maxiter)
}

cpp_sc05Z <- function(D, K, nnbd, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc05Z', PACKAGE = 'T4cluster', D, K, nnbd, usekmeans, maxiter)
}

cpp_sc09G <- function(D, K, nnbd, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc09G', PACKAGE = 'T4cluster', D, K, nnbd, usekmeans, maxiter)
}

cpp_sc10Z <- function(D, K, usekmeans, maxiter) {
    .Call('_T4cluster_cpp_sc10Z', PACKAGE = 'T4cluster', D, K, usekmeans, maxiter)
}

cpp_sc11Y <- function(idmat, distmat, K, usekmeans, maxiter, rho) {
    .Call('_T4cluster_cpp_sc11Y', PACKAGE = 'T4cluster', idmat, distmat, K, usekmeans, maxiter, rho)
}

cpp_sc12L <- function(D, K, usekmeans, maxiter, sigma) {
    .Call('_T4cluster_cpp_sc12L', PACKAGE = 'T4cluster', D, K, usekmeans, maxiter, sigma)
}

fast_loss_prj <- function(nS, dS, mS, PS, xS, muS) {
    .Call('_T4cluster_fast_loss_prj', PACKAGE = 'T4cluster', nS, dS, mS, PS, xS, muS)
}

cpp_shortestpath <- function(locs, dists) {
    .Call('_T4cluster_cpp_shortestpath', PACKAGE = 'T4cluster', locs, dists)
}

cpp_pdist <- function(X, p) {
    .Call('_T4cluster_cpp_pdist', PACKAGE = 'T4cluster', X, p)
}

cpp_pdist2 <- function(X, Y, p) {
    .Call('_T4cluster_cpp_pdist2', PACKAGE = 'T4cluster', X, Y, p)
}

cpp_pdistMP <- function(X, p, nCores) {
    .Call('_T4cluster_cpp_pdistMP', PACKAGE = 'T4cluster', X, p, nCores)
}

cpp_sample <- function(N, m, prob, replace) {
    .Call('_T4cluster_cpp_sample', PACKAGE = 'T4cluster', N, m, prob, replace)
}

cpp_setdiff <- function(x, y) {
    .Call('_T4cluster_cpp_setdiff', PACKAGE = 'T4cluster', x, y)
}

label_kmeans <- function(data, K, maxiter) {
    .Call('_T4cluster_label_kmeans', PACKAGE = 'T4cluster', data, K, maxiter)
}

label_gmm <- function(data, K, maxiter) {
    .Call('_T4cluster_label_gmm', PACKAGE = 'T4cluster', data, K, maxiter)
}

sc_unnormalized <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_unnormalized', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

sc_normalNJW <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_normalNJW', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

sc_normalSM <- function(W, K, usekmeans, maxiter) {
    .Call('_T4cluster_sc_normalSM', PACKAGE = 'T4cluster', W, K, usekmeans, maxiter)
}

gmm_predict <- function(X, oldweight, oldmeans, oldcovs) {
    .Call('_T4cluster_gmm_predict', PACKAGE = 'T4cluster', X, oldweight, oldmeans, oldcovs)
}

gmm_sample <- function(n, oldweight, oldmeans, oldcovs) {
    .Call('_T4cluster_gmm_sample', PACKAGE = 'T4cluster', n, oldweight, oldmeans, oldcovs)
}

gmm_loglkd <- function(X, oldweight, oldmeans, oldcovs) {
    .Call('_T4cluster_gmm_loglkd', PACKAGE = 'T4cluster', X, oldweight, oldmeans, oldcovs)
}

gauss_rmvnorm <- function(N, mu, var) {
    .Call('_T4cluster_gauss_rmvnorm', PACKAGE = 'T4cluster', N, mu, var)
}

